src/main.rs, src/search.rs, src/util.rs
```
Score of dev vs master: 687 - 550 - 830  [0.533] 2067
...      dev playing White: 443 - 192 - 399  [0.621] 1034
...      dev playing Black: 244 - 358 - 431  [0.445] 1033
...      White vs Black: 801 - 436 - 830  [0.588] 2067
Elo difference: 23.1 +/- 11.6, LOS: 100.0 %, DrawRatio: 40.2 %
```
=> History gravity

src/main.rs, src/position.rs, src/util.rs
Speed boost + idc about frc anymore
=> Remove FRC to save space

README.md, src/search.rs
=> 3 Fold Draw Detection on Root

src/search.rs
ELO   | 13.18 +- 7.87 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4720 W: 1579 L: 1400 D: 1741
https://chess.swehosting.se/test/2181/
Bench: 6735522
=> update best move on fail high aspiration search,

Cargo.toml, README.md, src/main.rs
ELO   | 150.10 +- 12.36 (95%)
CONF  | 60.0+0.60s Threads=1 Hash=128MB
GAMES | N: 2000 W: 1019 L: 205 D: 776
https://chess.swehosting.se/test/2280/
Bench: 13055552
=> 0.4.0 Release

src/search.rs
=> Static Exchange Evaluation Pruning in Quiescence Search

src/search.rs
=> Quiet SEE Pruning

src/search.rs
=> Improving in Quiet LMP

src/search.rs
=> More SEE pruning in qsearch

src/search.rs
=> Singular Extensions

src/search.rs
No Functional Change
Bench: 7290955
=> Cleanup Singular Extensions

src/search.rs
=> TT in QSearch

src/main.rs, src/search.rs
=> Counter Moves

src/main.rs
=> Widen Hard - Soft Bounds

src/search.rs
=> Remove `null` bool

src/search.rs
=> Yeet Null Bool

datagen/src/main.rs, tuner/src/core/params.rs, tuner/src/core/score.rs
=> Cleanup Datagen and Tuning

akimbo/src/main.rs, akimbo/src/position.rs, tuner/src/core/position.rs
=> Test mobility

Cargo.toml
=> Update workspace resolver

datagen/src/thread.rs
=> Datagen Fix

akimbo/src/search.rs, akimbo/src/tables.rs
=> Double Extensions

akimbo/src/search.rs, akimbo/src/tables.rs
=> Continuation History

akimbo/src/search.rs, akimbo/src/tables.rs
=> Counter Move History

akimbo/src/lib.rs, akimbo/src/tables.rs
=> Construct Continuation History Directly on Heap

akimbo/src/attacks.rs, akimbo/src/position.rs, akimbo/src/search.rs, akimbo/src/tables.rs
=> Threat History

akimbo/src/search.rs, akimbo/src/tables.rs
=> Simplify away Counter Moves

akimbo/src/search.rs, akimbo/src/tables.rs
=> 1 Killer per ply

src/datagen.rs, src/frc.rs, src/moves.rs, src/position.rs, src/search.rs, src/thread.rs, src/uci.rs
=> Rework Castling

src/search.rs, src/thread.rs
=> NMP Verification Search

src/search.rs
Elo   | 2.29 +- 2.28 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 41474 W: 9846 L: 9573 D: 22055
Penta | [184, 4774, 10588, 4967, 224]
https://chess.swehosting.se/test/5709/
Bench: 2399226
=> Negative Extension Tweak

src/position.rs, src/search.rs
=> NMP Non-Pawn-King Condition

src/network.rs
=> Support `EVALFILE`

src/eval.rs, src/position.rs
Elo   | 19.47 +- 8.60 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2590 W: 748 L: 603 D: 1239
Penta | [51, 249, 562, 370, 63]
https://chess.swehosting.se/test/7689/
Bench: 3677693
=> UE the PSTs

src/consts.rs, src/position.rs, src/search.rs, src/tables.rs, src/thread.rs, src/uci.rs
Elo   | 20.59 +- 8.74 (95%)
SPRT  | 20.0+0.20s Threads=1 Hash=32MB
LLR   | 2.93 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2314 W: 631 L: 494 D: 1189
Penta | [32, 231, 511, 334, 49]
https://chess.swehosting.se/test/7693/
3451412
=> Hce corrhist
